//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.22 at 06:35:38 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://savelyeva.it.by/jd_02_09/task_c/xml/persons", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.savelyeva.jd_02_09.task_c.xml.persons;
