//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.25 at 08:49:05 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://generate.taskc_generate.jd_02_09.artiuschik.it.by/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.artiuschik.jd_02_09.taskc_generate.generate;
