//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.22 at 10:01:13 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://C_AutoConvert.jd02_09_JAXB.XML.rudzko.it.by/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.rudzko.XML.jd02_09_JAXB.C_AutoConvert;
