//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.22 at 10:01:13 PM MSK 
//


package by.it.rudzko.XML.jd02_09_JAXB.C_AutoConvert;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for periodicals complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="periodicals">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="journals" type="{http://C_AutoConvert.jd02_09_JAXB.XML.rudzko.it.by/}journals"/>
 *         &lt;element name="papers" type="{http://C_AutoConvert.jd02_09_JAXB.XML.rudzko.it.by/}papers"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "periodicals", propOrder = {
    "journals",
    "papers"
})
public class Periodicals {

    @XmlElement(required = true)
    protected Journals journals;
    @XmlElement(required = true)
    protected Papers papers;

    /**
     * Gets the value of the journals property.
     * 
     * @return
     *     possible object is
     *     {@link Journals }
     *     
     */
    public Journals getJournals() {
        return journals;
    }

    /**
     * Sets the value of the journals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Journals }
     *     
     */
    public void setJournals(Journals value) {
        this.journals = value;
    }

    /**
     * Gets the value of the papers property.
     * 
     * @return
     *     possible object is
     *     {@link Papers }
     *     
     */
    public Papers getPapers() {
        return papers;
    }

    /**
     * Sets the value of the papers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Papers }
     *     
     */
    public void setPapers(Papers value) {
        this.papers = value;
    }

}
