//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.22 at 10:01:13 PM MSK 
//


package by.it.rudzko.XML.jd02_09_JAXB.C_AutoConvert;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ru_or_blr.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ru_or_blr">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="blr"/>
 *     &lt;enumeration value="ru"/>
 *     &lt;enumeration value="ru_blr"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ru_or_blr")
@XmlEnum
public enum RuOrBlr {

    @XmlEnumValue("blr")
    BLR("blr"),
    @XmlEnumValue("ru")
    RU("ru"),
    @XmlEnumValue("ru_blr")
    RU_BLR("ru_blr");
    private final String value;

    RuOrBlr(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RuOrBlr fromValue(String v) {
        for (RuOrBlr c: RuOrBlr.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
