//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 12:26:46 PM MSK 
//


package by.it.rudzko.jd03_02.POJO;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for myDataBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="myDataBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Roles" type="{http://POJO.rudzko.it.by/}Roles"/>
 *         &lt;element name="Users" type="{http://POJO.rudzko.it.by/}Users"/>
 *         &lt;element name="Readership" type="{http://POJO.rudzko.it.by/}Readership"/>
 *         &lt;element name="Periodicals" type="{http://POJO.rudzko.it.by/}Periodicals"/>
 *         &lt;element name="Subscription" type="{http://POJO.rudzko.it.by/}Subscription"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "myDataBase", propOrder = {

})
public class MyDataBase {

    @XmlElement(name = "Roles", required = true)
    protected Roles roles;
    @XmlElement(name = "Users", required = true)
    protected Users users;
    @XmlElement(name = "Readership", required = true)
    protected Readership readership;
    @XmlElement(name = "Periodicals", required = true)
    protected Periodicals periodicals;
    @XmlElement(name = "Subscription", required = true)
    protected Subscription subscription;

    /**
     * Gets the value of the roles property.
     * 
     * @return
     *     possible object is
     *     {@link Roles }
     *     
     */
    public Roles getRoles() {
        return roles;
    }

    /**
     * Sets the value of the roles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Roles }
     *     
     */
    public void setRoles(Roles value) {
        this.roles = value;
    }

    /**
     * Gets the value of the users property.
     * 
     * @return
     *     possible object is
     *     {@link Users }
     *     
     */
    public Users getUsers() {
        return users;
    }

    /**
     * Sets the value of the users property.
     * 
     * @param value
     *     allowed object is
     *     {@link Users }
     *     
     */
    public void setUsers(Users value) {
        this.users = value;
    }

    /**
     * Gets the value of the readership property.
     * 
     * @return
     *     possible object is
     *     {@link Readership }
     *     
     */
    public Readership getReadership() {
        return readership;
    }

    /**
     * Sets the value of the readership property.
     * 
     * @param value
     *     allowed object is
     *     {@link Readership }
     *     
     */
    public void setReadership(Readership value) {
        this.readership = value;
    }

    /**
     * Gets the value of the periodicals property.
     * 
     * @return
     *     possible object is
     *     {@link Periodicals }
     *     
     */
    public Periodicals getPeriodicals() {
        return periodicals;
    }

    /**
     * Sets the value of the periodicals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Periodicals }
     *     
     */
    public void setPeriodicals(Periodicals value) {
        this.periodicals = value;
    }

    /**
     * Gets the value of the subscription property.
     * 
     * @return
     *     possible object is
     *     {@link Subscription }
     *     
     */
    public Subscription getSubscription() {
        return subscription;
    }

    /**
     * Sets the value of the subscription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subscription }
     *     
     */
    public void setSubscription(Subscription value) {
        this.subscription = value;
    }

}
