//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 12:26:46 PM MSK 
//


package by.it.rudzko.jd03_02.POJO;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.it.rudzko.pojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MyDataBase_QNAME = new QName("http://POJO.rudzko.it.by/", "myDataBase");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.it.rudzko.pojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MyDataBase }
     * 
     */
    public MyDataBase createMyDataBase() {
        return new MyDataBase();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Readership }
     * 
     */
    public Readership createReadership() {
        return new Readership();
    }

    /**
     * Create an instance of {@link Subscr }
     * 
     */
    public Subscr createSubscr() {
        return new Subscr();
    }

    /**
     * Create an instance of {@link Audience }
     * 
     */
    public Audience createAudience() {
        return new Audience();
    }

    /**
     * Create an instance of {@link Periodical }
     * 
     */
    public Periodical createPeriodical() {
        return new Periodical();
    }

    /**
     * Create an instance of {@link Roles }
     * 
     */
    public Roles createRoles() {
        return new Roles();
    }

    /**
     * Create an instance of {@link Users }
     * 
     */
    public Users createUsers() {
        return new Users();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Periodicals }
     * 
     */
    public Periodicals createPeriodicals() {
        return new Periodicals();
    }

    /**
     * Create an instance of {@link Subscription }
     * 
     */
    public Subscription createSubscription() {
        return new Subscription();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MyDataBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://POJO.rudzko.it.by/", name = "myDataBase")
    public JAXBElement<MyDataBase> createMyDataBase(MyDataBase value) {
        return new JAXBElement<MyDataBase>(_MyDataBase_QNAME, MyDataBase.class, null, value);
    }

}
