//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 12:26:46 PM MSK 
//


package by.it.rudzko.jd03_02.POJO;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Role complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="Role">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Participant" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Role", propOrder = {
        "id",
        "participant"
})
public class Role {

    @XmlElement(name = "ID")
    protected int id;
    @XmlElement(name = "Participant", required = true)
    private String participant;

    /**
     * Gets the value of the id property.
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the participant property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getParticipant() {
        return this.participant;
    }

    /**
     * Sets the value of the participant property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setParticipant(String value) {
        this.participant = value;
    }

    @Override
    public int hashCode() {
        return this.id + this.participant.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (obj == this) return true;
        if (obj instanceof Role) {
            Role r = (Role) obj;
            return (this.id == r.id && this.participant.equalsIgnoreCase(r.participant));
        } else return false;
    }

    @Override
    public String toString() {
        return this.participant;
    }
}
