//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 12:26:46 PM MSK 
//


package by.it.rudzko.jd03_02.POJO;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Subscr complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="Subscr">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Periodical" type="{http://POJO.rudzko.it.by/}Periodical"/>
 *         &lt;element name="Subscriber" type="{http://POJO.rudzko.it.by/}User"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Subscr", propOrder = {
        "id",
        "periodical",
        "subscriber"
})
public class Subscr {

    @XmlElement(name = "ID")
    protected int id;
    @XmlElement(name = "Periodical", required = true)
    protected Periodical periodical;
    @XmlElement(name = "Subscriber", required = true)
    private User subscriber;

    /**
     * Gets the value of the id property.
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the periodical property.
     *
     * @return possible object is
     * {@link Periodical }
     */
    public Periodical getPeriodical() {
        return this.periodical;
    }

    /**
     * Sets the value of the periodical property.
     *
     * @param value allowed object is
     *              {@link Periodical }
     */
    public void setPeriodical(Periodical value) {
        this.periodical = value;
    }

    /**
     * Gets the value of the subscriber property.
     *
     * @return possible object is
     * {@link User }
     */
    public User getSubscriber() {
        return this.subscriber;
    }

    /**
     * Sets the value of the subscriber property.
     *
     * @param value allowed object is
     *              {@link User }
     */
    public void setSubscriber(User value) {
        this.subscriber = value;
    }

    @Override
    public int hashCode() {
        return this.periodical.hashCode() + this.subscriber.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (obj == this) return true;
        if (obj instanceof Subscr) {
            Subscr s = (Subscr) obj;
            return (this.id == s.id && this.periodical.equals(s.periodical) && this.subscriber.equals(s.subscriber));
        } else return false;
    }

    @Override
    public String toString() {
        return this.subscriber + " subscribed to " + this.periodical;
    }
}
