//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 12:26:46 PM MSK 
//


package by.it.rudzko.jd03_02.POJO;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Subscription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Subscription">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Subscr" type="{http://POJO.rudzko.it.by/}Subscr" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Subscription", propOrder = {
    "subscr"
})
class Subscription {

    @XmlElement(name = "Subscr", required = true)
    private List<Subscr> subscr;

    /**
     * Gets the value of the subscr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subscr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubscr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subscr }
     * 
     * 
     */
    List<Subscr> getSubscr() {
        if (subscr == null) {
            subscr = new ArrayList<>();
        }
        return this.subscr;
    }

    void setSubscr(List<Subscr> subscr) {
        this.subscr = subscr;
    }

    @Override
    public int hashCode() {
        int hc=1;
        for (Subscr s:
                subscr) {
            hc+=s.hashCode();
        }
        return hc;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (obj == this) return true;
        if (obj instanceof Subscription) {
            Subscription s = (Subscription) obj;
            return (this.subscr.equals(s.subscr));
        } else return false;
    }

    @Override
    public String toString() {
        return this.subscr.toString();
    }
}
