//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.23 at 11:15:24 AM MSK 
//


package by.it.emelyanov.jd02_09.xml.hotels;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Hotel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Hotel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Clients">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="client" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="passport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="login" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="client_id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Apartments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="apartment" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="floor" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="room_number" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="places" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="apartment_id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Orders">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="order" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="user_id" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="apartment_id" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="arrive_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="return_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="bill" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="order_id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Hotel", propOrder = {
    "clients",
    "apartments",
    "orders"
})
public class Hotel {

    @XmlElement(name = "Clients", required = true)
    protected Hotel.Clients clients;
    @XmlElement(name = "Apartments", required = true)
    protected Hotel.Apartments apartments;
    @XmlElement(name = "Orders", required = true)
    protected Hotel.Orders orders;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the clients property.
     * 
     * @return
     *     possible object is
     *     {@link Hotel.Clients }
     *     
     */
    public Hotel.Clients getClients() {
        return clients;
    }

    /**
     * Sets the value of the clients property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hotel.Clients }
     *     
     */
    public void setClients(Hotel.Clients value) {
        this.clients = value;
    }

    /**
     * Gets the value of the apartments property.
     * 
     * @return
     *     possible object is
     *     {@link Hotel.Apartments }
     *     
     */
    public Hotel.Apartments getApartments() {
        return apartments;
    }

    /**
     * Sets the value of the apartments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hotel.Apartments }
     *     
     */
    public void setApartments(Hotel.Apartments value) {
        this.apartments = value;
    }

    /**
     * Gets the value of the orders property.
     * 
     * @return
     *     possible object is
     *     {@link Hotel.Orders }
     *     
     */
    public Hotel.Orders getOrders() {
        return orders;
    }

    /**
     * Sets the value of the orders property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hotel.Orders }
     *     
     */
    public void setOrders(Hotel.Orders value) {
        this.orders = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="apartment" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="floor" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="room_number" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="places" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="apartment_id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "apartment"
    })
    public static class Apartments {

        protected List<Hotel.Apartments.Apartment> apartment;

        /**
         * Gets the value of the apartment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the apartment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getApartment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Hotel.Apartments.Apartment }
         * 
         * 
         */
        public List<Hotel.Apartments.Apartment> getApartment() {
            if (apartment == null) {
                apartment = new ArrayList<Hotel.Apartments.Apartment>();
            }
            return this.apartment;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="floor" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="room_number" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="places" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="apartment_id" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "floor",
            "roomNumber",
            "places",
            "category",
            "cost",
            "status"
        })
        public static class Apartment {

            protected float floor;
            @XmlElement(name = "room_number")
            protected float roomNumber;
            protected float places;
            @XmlElement(required = true)
            protected String category;
            protected float cost;
            @XmlElement(required = true)
            protected String status;
            @XmlAttribute(name = "apartment_id")
            protected Byte apartmentId;

            /**
             * Gets the value of the floor property.
             * 
             */
            public float getFloor() {
                return floor;
            }

            /**
             * Sets the value of the floor property.
             * 
             */
            public void setFloor(float value) {
                this.floor = value;
            }

            /**
             * Gets the value of the roomNumber property.
             * 
             */
            public float getRoomNumber() {
                return roomNumber;
            }

            /**
             * Sets the value of the roomNumber property.
             * 
             */
            public void setRoomNumber(float value) {
                this.roomNumber = value;
            }

            /**
             * Gets the value of the places property.
             * 
             */
            public float getPlaces() {
                return places;
            }

            /**
             * Sets the value of the places property.
             * 
             */
            public void setPlaces(float value) {
                this.places = value;
            }

            /**
             * Gets the value of the category property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCategory() {
                return category;
            }

            /**
             * Sets the value of the category property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCategory(String value) {
                this.category = value;
            }

            /**
             * Gets the value of the cost property.
             * 
             */
            public float getCost() {
                return cost;
            }

            /**
             * Sets the value of the cost property.
             * 
             */
            public void setCost(float value) {
                this.cost = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatus() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatus(String value) {
                this.status = value;
            }

            /**
             * Gets the value of the apartmentId property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getApartmentId() {
                return apartmentId;
            }

            /**
             * Sets the value of the apartmentId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setApartmentId(Byte value) {
                this.apartmentId = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="client" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="passport" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="login" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="client_id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "client"
    })
    public static class Clients {

        protected List<Hotel.Clients.Client> client;

        /**
         * Gets the value of the client property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the client property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClient().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Hotel.Clients.Client }
         * 
         * 
         */
        public List<Hotel.Clients.Client> getClient() {
            if (client == null) {
                client = new ArrayList<Hotel.Clients.Client>();
            }
            return this.client;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="passport" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="login" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="client_id" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "surname",
            "middleName",
            "email",
            "passport",
            "login",
            "password"
        })
        public static class Client {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String surname;
            @XmlElement(required = true)
            protected String middleName;
            @XmlElement(required = true)
            protected String email;
            @XmlElement(required = true)
            protected String passport;
            @XmlElement(required = true)
            protected String login;
            @XmlElement(required = true)
            protected String password;
            @XmlAttribute(name = "client_id")
            protected Byte clientId;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the surname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSurname() {
                return surname;
            }

            /**
             * Sets the value of the surname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSurname(String value) {
                this.surname = value;
            }

            /**
             * Gets the value of the middleName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMiddleName() {
                return middleName;
            }

            /**
             * Sets the value of the middleName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMiddleName(String value) {
                this.middleName = value;
            }

            /**
             * Gets the value of the email property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEmail() {
                return email;
            }

            /**
             * Sets the value of the email property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEmail(String value) {
                this.email = value;
            }

            /**
             * Gets the value of the passport property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassport() {
                return passport;
            }

            /**
             * Sets the value of the passport property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPassport(String value) {
                this.passport = value;
            }

            /**
             * Gets the value of the login property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLogin() {
                return login;
            }

            /**
             * Sets the value of the login property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLogin(String value) {
                this.login = value;
            }

            /**
             * Gets the value of the password property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassword() {
                return password;
            }

            /**
             * Sets the value of the password property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPassword(String value) {
                this.password = value;
            }

            /**
             * Gets the value of the clientId property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getClientId() {
                return clientId;
            }

            /**
             * Sets the value of the clientId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setClientId(Byte value) {
                this.clientId = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="order" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="user_id" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="apartment_id" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="arrive_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="return_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="bill" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="order_id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "order"
    })
    public static class Orders {

        protected List<Hotel.Orders.Order> order;

        /**
         * Gets the value of the order property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the order property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrder().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Hotel.Orders.Order }
         * 
         * 
         */
        public List<Hotel.Orders.Order> getOrder() {
            if (order == null) {
                order = new ArrayList<Hotel.Orders.Order>();
            }
            return this.order;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="user_id" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="apartment_id" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="arrive_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="return_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="bill" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *       &lt;/sequence>
         *       &lt;attribute name="order_id" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "userId",
            "apartmentId",
            "arriveDate",
            "returnDate",
            "bill"
        })
        public static class Order {

            @XmlElement(name = "user_id")
            protected float userId;
            @XmlElement(name = "apartment_id")
            protected float apartmentId;
            @XmlElement(name = "arrive_date", required = true)
            protected String arriveDate;
            @XmlElement(name = "return_date", required = true)
            protected String returnDate;
            protected float bill;
            @XmlAttribute(name = "order_id")
            protected Byte orderId;

            /**
             * Gets the value of the userId property.
             * 
             */
            public float getUserId() {
                return userId;
            }

            /**
             * Sets the value of the userId property.
             * 
             */
            public void setUserId(float value) {
                this.userId = value;
            }

            /**
             * Gets the value of the apartmentId property.
             * 
             */
            public float getApartmentId() {
                return apartmentId;
            }

            /**
             * Sets the value of the apartmentId property.
             * 
             */
            public void setApartmentId(float value) {
                this.apartmentId = value;
            }

            /**
             * Gets the value of the arriveDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getArriveDate() {
                return arriveDate;
            }

            /**
             * Sets the value of the arriveDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setArriveDate(String value) {
                this.arriveDate = value;
            }

            /**
             * Gets the value of the returnDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReturnDate() {
                return returnDate;
            }

            /**
             * Sets the value of the returnDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReturnDate(String value) {
                this.returnDate = value;
            }

            /**
             * Gets the value of the bill property.
             * 
             */
            public float getBill() {
                return bill;
            }

            /**
             * Sets the value of the bill property.
             * 
             */
            public void setBill(float value) {
                this.bill = value;
            }

            /**
             * Gets the value of the orderId property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getOrderId() {
                return orderId;
            }

            /**
             * Sets the value of the orderId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setOrderId(Byte value) {
                this.orderId = value;
            }

        }

    }

}
