//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.23 at 11:15:24 AM MSK 
//


package by.it.emelyanov.jd02_09.xml.hotels;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.it.emelyanov.jd02_09.xml.hotels package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.it.emelyanov.jd02_09.xml.hotels
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Hotel }
     * 
     */
    public Hotel createHotel() {
        return new Hotel();
    }

    /**
     * Create an instance of {@link Hotel.Orders }
     * 
     */
    public Hotel.Orders createHotelOrders() {
        return new Hotel.Orders();
    }

    /**
     * Create an instance of {@link Hotel.Apartments }
     * 
     */
    public Hotel.Apartments createHotelApartments() {
        return new Hotel.Apartments();
    }

    /**
     * Create an instance of {@link Hotel.Clients }
     * 
     */
    public Hotel.Clients createHotelClients() {
        return new Hotel.Clients();
    }

    /**
     * Create an instance of {@link Hotels }
     * 
     */
    public Hotels createHotels() {
        return new Hotels();
    }

    /**
     * Create an instance of {@link Hotel.Orders.Order }
     * 
     */
    public Hotel.Orders.Order createHotelOrdersOrder() {
        return new Hotel.Orders.Order();
    }

    /**
     * Create an instance of {@link Hotel.Apartments.Apartment }
     * 
     */
    public Hotel.Apartments.Apartment createHotelApartmentsApartment() {
        return new Hotel.Apartments.Apartment();
    }

    /**
     * Create an instance of {@link Hotel.Clients.Client }
     * 
     */
    public Hotel.Clients.Client createHotelClientsClient() {
        return new Hotel.Clients.Client();
    }

}
