//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.23 at 11:15:24 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jd02_09.emelyanov.it.by/xml/Hotels", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.emelyanov.jd02_09.xml.hotels;
