package by.it.savelyeva.jd_01_12;

/**
 * Created by nato on 9/28/16.
 */
@Deprecated
public class Data {
	public static final String novell = "In the ancient city of London, "
			+ "on a certain autumn day in the second quarter of the sixteenth century, "
			+ "a boy was born to a poor family of the name of Canty, who did not want him.  "
			+ "On the same day another English child was born to a rich family of the name of Tudor, who did want him. "
			+ "All England wanted him too.  "
			+ "England had so longed for him, and hoped for him, and prayed God for him, "
			+ "that, now that he was really come, the people went nearly mad for joy.  "
			+ "Mere acquaintances hugged and kissed each other and cried. "
			+ "Everybody took a holiday, and high and low, rich and poor, "
			+ "feasted and danced and sang, and got very mellow; "
			+ "and they kept this up for days and nights together.  "
			+ "By day, London was a sight to see, with gay banners waving from every balcony and housetop, "
			+ "and splendid pageants marching along.  "
			+ "By night, it was again a sight to see, with its great bonfires at every corner, "
			+ "and its troops of revellers making merry around them.  "
			+ "There was no talk in all England but of the new baby, Edward Tudor, Prince of Wales, "
			+ "who lay lapped in silks and satins, unconscious of all this fuss, "
			+ "and not knowing that great lords and ladies were tending him "
			+ "and watching over him�and not caring, either.  "
			+ "But there was no talk about the other baby, Tom Canty, lapped in his poor rags, "
			+ "except among the family of paupers whom he had just come to trouble with his presence."
			+ "Let us skip a number of years. "
			+ "London was fifteen hundred years old, and was a great town�for that day. "
			+ "It had a hundred thousand inhabitants�some think double as many.  "
			+ "The streets were very 2narrow, and crooked, and dirty, especially in the part where Tom Canty lived, "
			+ "which was not far from London Bridge.  "
			+ "The houses were of wood, with the second story projecting over the first, "
			+ "and the third sticking its elbows out beyond the second.  "
			+ "The higher the houses grew, the broader they grew.  "
			+ "They were skeletons of strong criss-cross beams, with solid material between, coated with plaster.  "
			+ "The beams were painted red or blue or black, according to the owner's taste, "
			+ "and this gave the houses a very picturesque look.  "
			+ "The windows were small, glazed with little diamond-shaped panes, "
			+ "and they opened outward, on hinges, like doors. "
			+ "The house which Tom's father lived in was up a foul little pocket called Offal Court, "
			+ "out of Pudding Lane.  "
			+ "It was small, decayed, and rickety, but it was packed full of wretchedly poor families. "
			+ "Canty's tribe occupied a room on the third floor.  "
			+ "The mother and father had a sort of bedstead in the corner; "
			+ "but Tom, his grandmother, and his two sisters, "
			+ "Bet and Nan, were not restricted�they had all the floor to themselves, "
			+ "and might sleep where they chose.  "
			+ "There were the remains of a blanket or two, and some bundles of ancient and dirty straw, "
			+ "but these could not rightly be called beds, for they were not organised; "
			+ "they were kicked into a general pile, mornings, and selections made from the mass at night, for service.";
}
