//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.22 at 10:01:13 PM MSK 
//


package by.it.rudzko.XML.jd02_10_JSON.AB_XMLtoJSON;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for journal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="journal">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://C_AutoConvert.jd02_09_JAXB.XML.rudzko.it.by/}characteristics"/>
 *       &lt;attribute name="language" type="{http://C_AutoConvert.jd02_09_JAXB.XML.rudzko.it.by/}ru_or_blr" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "journal", propOrder = {
    "name",
    "topic",
    "frequency",
    "site",
    "index"
})
public class Journal {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String topic;
    @XmlElement(required = true)
    protected String frequency;
    @XmlElement(required = true)
    protected String site;
    @XmlSchemaType(name = "integer")
    protected int index;
    @XmlAttribute(name = "language")
    protected RuOrBlr language;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the topic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopic() {
        return topic;
    }

    /**
     * Sets the value of the topic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopic(String value) {
        this.topic = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequency(String value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the site property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSite() {
        return site;
    }

    /**
     * Sets the value of the site property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSite(String value) {
        this.site = value;
    }

    /**
     * Gets the value of the index property.
     * 
     */
    public int getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     */
    public void setIndex(int value) {
        this.index = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link RuOrBlr }
     *     
     */
    public RuOrBlr getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuOrBlr }
     *     
     */
    public void setLanguage(RuOrBlr value) {
        this.language = value;
    }
    @Override
    public String toString() {
        return "\nJournal: "+name+"\nTopics: "+topic+"\nFrequency: "+frequency+"\nSite: "+site+"\nIndex: "+index+"\nLanguage: "+language+"\n";
    }
}
