//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.22 at 10:01:13 PM MSK 
//


package by.it.rudzko.XML.jd02_10_JSON.AB_XMLtoJSON;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.it.rudzko.xml.jd02_09_jaxb.c_autoconvert package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Periodicals_QNAME = new QName("http://C_AutoConvert.jd02_09_JAXB.XML.rudzko.it.by/", "periodicals");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.it.rudzko.xml.jd02_09_jaxb.c_autoconvert
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Periodicals }
     * 
     */
    public Periodicals createPeriodicals() {
        return new Periodicals();
    }

    /**
     * Create an instance of {@link Journal }
     * 
     */
    public Journal createJournal() {
        return new Journal();
    }

    /**
     * Create an instance of {@link Paper }
     * 
     */
    public Paper createPaper() {
        return new Paper();
    }

    /**
     * Create an instance of {@link Journals }
     *
     */
    public Journals createJournals() {
        return new Journals();
    }

    /**
     * Create an instance of {@link Papers }
     *
     */
    public Papers createPapers() {
        return new Papers();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Periodicals }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://C_AutoConvert.jd02_09_JAXB.XML.rudzko.it.by/", name = "periodicals")
    public JAXBElement<Periodicals> createPeriodicals(Periodicals value) {
        return new JAXBElement<Periodicals>(_Periodicals_QNAME, Periodicals.class, null, value);
    }

}
