//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.30 at 04:44:30 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tests_generated.extra.jd_03_02.artiuschik.it.by/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.artiuschik.jd_03_02.extra.tests_generated;
